include: package:flutter_lints/flutter.yaml

linter:
  rules:
    sort_pub_dependencies: false
    prefer_single_quotes: true
    avoid_redundant_argument_values: true
    camel_case_types: true
    constant_identifier_names: false